### ISSUE TITLE
The import HMSPrebuilt mentioned in the docs isn't shipped 

### ISSUE THREAD

**Issue by pedromdcr** [100mslive/100ms-web#673]
**Describe the bug**
The `@100mslive/roomkit-react` package ins't properly shipping with the HMSPrebuilt component or it isn't being picked up by Typescript

**To Reproduce**
1. Install roomkit as per docs [here](https://www.100ms.live/docs/javascript/v2/quickstart/prebuilt-quickstart#add-prebuilt-component)
2. Import the HMSPrebuilt component from the module as per link above
3. See error

**Expected behavior**
The component should be picked up when imported

**Screenshots**

Module correctly installed:
![Module correctly installed](https://github.com/100mslive/100ms-web/assets/17787141/f8d9de8b-ebdb-46d3-99d2-a099662b5665)

The issue:
![The error](https://github.com/100mslive/100ms-web/assets/17787141/aba3d76c-5713-4f51-97d6-1f60bf7c55fd)

**Setup & Dependencies:**
 - @100mslive/roomkit-react 0.1.3
 - React 18.2.0
 - Next.js 13.2.1
 - Typescript 4.9.5

**Additional context**
I've tried restarting the TS server and reinstalling the package to no avail.

**Comment by saikatmitra91** [comment]
Hey @pedromdcr  

The issue has been fixed in the latest version of `@100mslive/roomkit-react` 

Please upgrade the version to latest to get the above issue fixed. This issue was specific to typescript, adding the typescript ignore comment would have fixed the issue. Anyway this issue is fixed in latest version - `0.1.5`  

Thanks for reporting the issue.

**Comment by saikatmitra91** [comment]
marking the issue as closed.
